### PR TITLE
Lauri/bug/435 fix circular dependencies and document resolutions

### LINKED ISSUE #435: Fix Circular Dependencies and Document Resolutions
## 🧹 **Task Description** 

- **Task**: Fix circular dependencies in the project.  
- **Purpose**: Resolving circular dependencies improves code maintainability, prevents potential runtime issues, and enhances build performance.

---

## ✅ **Steps to Complete**

1. Identify the cause of the circular dependencies in the following files:
   - `features/NavigateHeroes/index.ts` → `features/NavigateHeroes/ui/HeroDevelopmentSidebar.tsx`
   - `shared/ui/v2/Feedback/index.ts` → `shared/ui/v2/Feedback/ui/FeedbackSideButton/FeedbackSideButton.tsx`
2. Refactor the dependencies to break the circular references, possibly by:
   - Extracting shared logic into a separate module.
   - Using dynamic imports where applicable.
   - Reorganizing module imports to reduce cross-referencing.
3. Test the application to ensure functionality remains intact.
4. Verify that no new circular dependencies are introduced.
5. Run the linter and dependency analyzer to confirm the issue is resolved. `npm run check:circular` & `npm run build`
6. Create a Pull Request with documentation explaining the issue, the changes made, and the reasoning behind the chosen solution.

---

## 📎 **Additional Information**

- **Relevant Documentation**: 

Image

- **Special Instructions**: Ensure all affected components still function as expected after refactoring.

### PR DESCRIPTION
**Pull request by LauriHiltunen**
## 📄 **Pull Request Overview**

closes #435 

## 🔧 **Changes Made**

- fixed 2 circular dependencies by reorganizing module imports
- moved the components from the NavigateHeroes to different folders in the NavigateHeroes to improve the document resolution.
- used dynamic imports in the HeroDevelopmentSidebar

---

## ✅ **Checklist Before Submission**

- **Functionality**: I have tested my code, and it works as expected.
- **JSDoc**: I have added or updated JSDoc comments for all relevant code.
- **Debugging**: No `console.log()` or other debugging statements are left.
- **Clean Code**: Removed commented-out or unnecessary code.
- **Tests**: Added new tests or updated existing ones for the changes made.
- **Documentation**: Documentation has been updated (if applicable).

---

## 📝 **Additional Information**

In both circular dependencies the issue was: importing from the index.ts inside the component. I imported the needed components relatively from elsewhere to break the circular dependencies. I used this method because this was the best for this case in my opinion.

I got inspired from the issue to use dynamic imports in the HeroDevelopementSidebar component from `features/NavigateHeroes` to make its performance better (I made new files for dynamic imports and tested in the storybook). I moved the NavigateHeroes components to different folders to improve the document resolution.

### Checked for circular dependencies
Näyttökuva 2025-04-01 135632

### Tested build
Näyttökuva 2025-04-01 135801

### CODE REVIEW

File: frontend-next-migration/src/features/NavigateHeroes/ui/HeroDevelopmentSidebar/HeroDevelopmentSidebar.tsx [hunk 1]
```diff
@@ -1,17 +1,18 @@
...
 import React from 'react';
+import useSizes from '@/shared/lib/hooks/useSizes';
+import HeroDevelopmentNavMenuAsDropdownAsync from '../HeroDevelopmentNavMenuAsDropdown/HeroDevelopmentNavMenuAsDropdown.async';
+import HeroNavMenuAsync from '../HeroNavMenu/HeroNavMenu.async';
 
 const HeroDevelopmentSidebar: React.FC = () => {
     const { isDesktopSize, isWidescreenSize } = useSizes();
 
     return isDesktopSize || isWidescreenSize ? (
         <div style={{ width: 'fit-content' }}>
```
Comment (Skoivumaki) [inline frontend-next-migration/src/features/NavigateHeroes/ui/HeroDevelopmentSidebar/HeroDevelopmentSidebar.tsx:11]: Remove inline CSS

**Review by Skoivumaki — CHANGES_REQUESTED** [review]
> I got inspired from the issue to use dynamic imports in the HeroDevelopementSidebar component from features/NavigateHeroes to make its performance better (I made new files for dynamic imports and tested in the storybook). 

Very nice!
Found no issues with code and circulars now gone. Also apologies for long review time, just fix the CSS issue 👍

**Review by Skoivumaki — APPROVED** [review]
