### PR TITLE
Liisa/enhancement/627 site wide bugs and UI improvements

### LINKED ISSUE #627: Enhancement: Site-Wide Bugs And UI Improvements
## 🐞 **Priority:** Medium

---

## 🚨 **Issue Description**

The goal of this issue is to fix layout bugs and improve the overall visual quality. Currently, several components suffer from inconsistent responsive behavior, specifically regarding internal container constraints on mobile devices.

---

### 1. Site-Wide

| Area | Device | Issue |
| :--- | :--- | :--- |
| **Layout** | Mobile | The page content exceeds the viewport width, causing unwanted horizontal scrolling. **Fix:** Audit page containers and ensure no fixed-width elements are breaking the responsive flow. |
| **Footer** | Mobile | **Component Overflow**: Text and links are bleeding over the component boundaries/edges. The content does not wrap or scale correctly within its parent container. **Fix:** Adjust flex/grid properties, margins, and padding. Ensure ```word-break``` or ```overflow-wrap``` is handled, or reduce font sizes for small screens. |

**Image References:**
Image

Image

---

### 2. News Pages

| Area | Device | Issue |
| :--- | :--- | :--- |
| **Sharing Button** | Desktop | **Hover State Alignment**: When hovering over the share button, the border is improperly positioned (too low relative to the content). The icon and text are not vertically centered, causing the border to clip against the component edges with zero margin.  **Fix:** Adjust padding and flex alignment to ensure the icon and text are perfectly centered. Ensure the hover border has adequate spacing (margins/padding) and a balanced visual appearance. |
| **"Read More" Section** | Mobile/Tablet |  On the single news page, the "Read More" title lacks any margin, causing it to sit flush against adjacent elements. **Fix:** Apply a **16px margin** to the "Read More" title as specified in the Figma design to ensure proper breathing room. |
| **News Image Assets** | All (High Res) |  The current image dimensions (100x600) are insufficient for larger displays, causing the images to appear blurry or pixelated. **Fix:** Update the image dimensions to 1024x1024 to ensure high-fidelity rendering across all screen sizes. **Target File**: ```frontend-next-migration\src\preparedPages\NewsPages\ui\NewsElementPage\ui\NewsElementPage.tsx``` |
| **News Card Assets** | All (High Res) |  The current image dimensions (100x600) are insufficient for larger displays, causing the images to appear blurry or pixelated. **Fix:** Update the image dimensions to 1024x1024 to ensure high-fidelity rendering across all screen sizes.  **Target File**: ```frontend-next-migration\src\widgets\NewsCard\ui\NewsCard.tsx``` |

**Image References:**
Image

Image

Image

---

### 3. Join Us Page

| Area | Device | Issue |
| :--- | :--- | :--- |
| **Social Media Icons** | All |  The icons are currently white, which makes them appear as static elements rather than interactive links. **Fix:** Change the icon color to the site's primary **orange**. Implement a **hover effect** (Desktop) consistent with the social media icons used in the Footer. |

**Image References:**
Image

---

### 4. Game Art Page

| Area | Device | Issue |
| :--- | :--- | :--- |
| **Game Art Page** | All | The page crashes immediately upon navigation in the local environment. **Fix:** Identify the Next.js ```Image``` component causing the crash. Add the missing ```width``` and ```height``` properties (or use ```fill```) to satisfy the Next.js boundary requirements. |
| **ScrollTop** | All | The ScrollTop button is rendered behind the page's text content, making it difficult to see or click. **Fix:** Increase the component's z-index to ensure it remains on the top layer above all other page content. |

**Image References:**
Image

Image

---

### 5. Team Page

| Area | Device | Issue |
| :--- | :--- | :--- |
| **ScrollTop** | Mobile/Tablet | The ScrollTop component has a z-index conflict, causing it to be hidden behind the page content. **Fix:** Adjust the z-index of the ScrollTop component to ensure it is layered correctly above all other elements on mobile and tablet. |
| **Team Header With Mosaic** | Desktop | The ```Team Header With Mosaic``` section is currently misaligned/off-center, creating an unbalanced visual layout. **Fix:** Center the section relative to the page container to ensure a symmetrical and polished appearance. |

**Image References:**
Image

Image

---

### 6. Clan Page + ChatBot

| Area | Device | Issue |
| :--- | :--- | :--- |
| **ScrollTop** | Mobile/Tablet | The ScrollTop button is rendered behind the ```MobileCard``` Title, making it difficult to see or click. **Fix:** Increase the component's z-index to ensure it remains on the top layer above all other page content.  |
| **ChatBot Button** | All | The ChatBot is currently out of service/not in use and should be disabled to prevent user confusion. **Fix:** Remove the ```ChatBotToggleButton``` component from the global layout located at ```app/[lng]/layout.tsx```.  |

**Image References:**
Image

---

## 🎯 **Documentation**

When creating the Pull Request for this enhancement, please **document all implemented changes clearly** to facilitate the review process.

### PR DESCRIPTION
**Pull request by davylis**
## 📄 **Pull Request Overview**

Closes #627

## 🔧 **Changes Made**

1. Updated multiple UI components and styles to improve layout consistency and responsiveness across the site. This includes:

- refining share button, footer rights, join-us icon hover, and news page spacing/styles
- stabilizing z-index for the scroll-to-top button
- improving feedback card sizing so inputs and buttons use responsive widths
- adjusting Team Header With Mosaic spacing by replacing the old desktop spacer approach with balanced left/right padding
- removing the chatbot toggle from the root layout

2. Refactored presentation package section typing and data shape:

- fixed `image` and `sidebarLogo` to structured objects with `src`, `alt`, `width`, and `height`
-updated `createSection`, related types, and section data to match the new structure

3. Improved image handling in news-related components by updating image dimensions.

4. Cleaned up legacy feedback styling by commenting out the old feedback card.

---

## ✅ **Checklist Before Submission**

- **Functionality**: I have tested my code, and it works as expected.
- **JSDoc**: I have added or updated JSDoc comments for all relevant code.
- **Debugging**: No `console.log()` or other debugging statements are left.
- **Clean Code**: Removed commented-out or unnecessary code.
- **Tests**: Added new tests or updated existing ones for the changes made.
- **Documentation**: Documentation has been updated (if applicable).

---

## 📝 **Additional Information**

Provide any additional context or information that reviewers may need to know:

- All needed done

### CODE REVIEW

File: frontend-next-migration/src/app/[lng]/layout.tsx [hunk 1]
```diff
@@ -128,7 +128,7 @@ export default function RootLayout(props: Props) {
                 <LayoutBackgroundController>
                     <Providers>
                         <FeedbackSideButton />
-                        <ChatBotToggleButton />
+                        {/* <ChatBotToggleButton /> */}
```
Comment (Rutjake) [inline frontend-next-migration/src/app/[lng]/layout.tsx]: We could have deleted this, but we can leave it in for a quick rollout, just in case it's needed later.

File: frontend-next-migration/src/features/Feedback/ui/FeedbackCard/FeedbackCard.module.scss [hunk 2]
```diff
@@ -1,80 +1,83 @@
-@import url('https://fonts.googleapis.com/css2?family=Joti+One&display=swap');
+//OLD FEEDBACK SCSS
```
Comment (Rutjake) [inline frontend-next-migration/src/features/Feedback/ui/FeedbackCard/FeedbackCard.module.scss]: Regarding the commented-out code: we should avoid leaving unused components commented out as it adds technical debt. It's better to either keep the component active or remove it entirely. Since we have a dedicated issue coming up for cleaning up old components, let's not leave it in a commented state—could you either revert the commenting or delete the file?

**Review by Rutjake — CHANGES_REQUESTED** [review]
Great work! Most of the bugs have been fixed, and the overall user experience of the site is improving significantly. However, a few things still need attention:

Mobile Responsiveness: The pages are still too wide for mobile screens. You can see this when "swiping" the mobile view sideways and the page wobbles horizontally.
Image

GameArt Page: This page still crashes in the local development environment, as we discussed earlier on Discord.
Image

See also the comments below.

File: frontend-next-migration/src/entities/PresentationPackages/model/data/artGameSections.ts [hunk 3]
```diff
@@ -36,11 +36,11 @@ export const ArtGameSections = i18nKeyPrefixes.map((key, index) =>
         prefix: key,
         index,
         image: {
-            src: imageSrcs[index],
+            src: imageSrcs[index] as unknown as string,
```
Comment (Rutjake) [inline frontend-next-migration/src/entities/PresentationPackages/model/data/artGameSections.ts:39]: It looks like the as unknown as string cast is used here to bypass a type mismatch between Next.js's StaticImageData and the expected string type.

Using double casting (as unknown as...) is generally considered a 'code smell' because it hides potential runtime issues and removes the benefits of TypeScript.

Recommendation:
Instead of forcing the type, we should update the interface or type definition for `ArtGameSections`

**Review by Rutjake — CHANGES_REQUESTED** [review]
Great work overall! I noticed one small thing regarding the typing. Check comment below for more details.

**Review by Rutjake — APPROVED** [review]
Good Work!

**Review by patinen — APPROVED** [review]
Good work overall.

Just for future reference: it would be safer to make image optional or map images by key instead of relying on index alignment.

In artGameSections.ts, EMPTY_IMAGE = '' feels like a workaround to keep indexes aligned between arrays. This is a bit fragile and may lead to issues with invalid image sources.
